/**
 * Data Loading & Processing
 */

// Fallback data if fetch fails
const FALLBACK_DATA = [
    { word: "ephemeral", definition: "lasting for a very short time", difficulty: 1200, pos: "a" },
    { word: "serendipity", definition: "occurrence of events by chance in a happy way", difficulty: 1200, pos: "n" },
    { word: "ubiquitous", definition: "present, appearing, or found everywhere", difficulty: 1300, pos: "a" }
];

export const loadWords = async () => {
    try {
        // Correct path to the CSV generated by Python script
        const response = await fetch('../data/processed/words.csv');
        if (!response.ok) throw new Error('Network response was not ok');
        
        const text = await response.text();
        return parseCSV(text);
    } catch (error) {
        console.warn('Failed to load CSV, using fallback data', error);
        return FALLBACK_DATA;
    }
};

const parseCSV = (csvText) => {
    const lines = csvText.split('\n');
    const words = [];
    
    // Skip header (index 0)
    for (let i = 1; i < lines.length; i++) {
        const line = lines[i].trim();
        if (!line) continue;
        
        // CSV parsing handling quoted strings
        // Format: word,original,pos,definition,example,rank,count,difficulty
        const parts = parseCSVLine(line);
        
        if (parts.length >= 8) {
            words.push({
                word: parts[0],
                pos: parts[2],
                definition: parts[3],
                difficulty: parseFloat(parts[7])
            });
        }
    }
    return words;
};

// Simple CSV parser that handles quoted fields
const parseCSVLine = (text) => {
    const result = [];
    let curValue = '';
    let inQuote = false;
    
    for (let i = 0; i < text.length; i++) {
        const char = text[i];
        
        if (char === '"') {
            inQuote = !inQuote;
        } else if (char === ',' && !inQuote) {
            result.push(curValue);
            curValue = '';
        } else {
            curValue += char;
        }
    }
    result.push(curValue);
    return result;
};
